# Generated by Django 5.1.6 on 2025-02-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ICAO", models.CharField(max_length=4, unique=True)),
                ("IATA", models.CharField(max_length=3, null=True)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
