# Generated by Django 5.1.7 on 2026-08-17 19:57

import django.core.validators
from django.db import migrations, models


def normalize_blank_iata_to_null(apps, schema_editor):
    # Must run before the unique constraint below: '' == '' would collide,
    # but NULL is always distinct from NULL under a unique index.
    Airport = apps.get_model("airports", "Airport")
    Airport.objects.filter(IATA="").update(IATA=None)


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            normalize_blank_iata_to_null, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="airport",
            name="IATA",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="IATA airport codes must be exactly 3 uppercase letters (e.g. LAX).",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="ICAO",
            field=models.CharField(
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ICAO airport codes must be exactly 4 uppercase letters (e.g. KLAX).",
                        regex="^[A-Z]{4}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(fields=["name"], name="airport_name_idx"),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(fields=["city"], name="airport_city_idx"),
        ),
    ]
