# Generated by Django 5.1.7 on 2026-08-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0002_alter_airport_iata_alter_airport_icao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ["name"]},
        ),
    ]
