# Generated by Django 5.1.7 on 2026-08-17 20:10

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0003_alter_airport_options"),
    ]

    operations = [
        # Enables Postgres's pg_trgm extension, which the GIN trigram
        # indexes below depend on. CREATE EXTENSION IF NOT EXISTS under the
        # hood, so it's harmless if another app's migration already ran this.
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="airport",
            name="airport_city_idx",
        ),
        migrations.AddIndex(
            model_name="airport",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="airport_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["city"],
                name="airport_city_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
