# Generated by Django 5.1.7 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0004_remove_airport_airport_city_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
