services:
  db:
    image: postgres:15
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avitrail
    ports:
      - "5432:5432"
    networks:
      - default
