services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: crow987/avitrail:latest
    volumes:
      - ./avitrail:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/avitrail
      - DEBUG=True
      - SECRET_KEY=secret
      - DJANGO_SETTINGS_MODULE=avitrail.settings.development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    command: >
      sh -c "python manage.py migrate --run-syncdb &&
             gunicorn avitrail.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:15
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avitrail
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
