# Generated by Django 5.1.6 on 2025-02-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0001_initial"),
        ("airports", "0001_initial"),
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airlines.airline"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_airport",
                to="airports.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_airport",
                to="airports.airport",
            ),
        ),
    ]
