# Generated by Django 5.1.7 on 2025-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="aircraft",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="tail_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
