# Generated by Django 5.1.7 on 2026-08-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0005_airline_disabled_at"),
        ("airports", "0005_airport_disabled_at"),
        ("flights", "0002_alter_flight_aircraft_alter_flight_tail_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airlines.airline"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arrival_airport",
                to="airports.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departure_airport",
                to="airports.airport",
            ),
        ),
    ]
