# Generated by Django 5.1.7 on 2026-08-17 19:57

import django.core.validators
from django.db import migrations, models


def normalize_blank_codes_to_null(apps, schema_editor):
    # Must run before the unique constraints below: '' == '' would collide,
    # but NULL is always distinct from NULL under a unique index.
    Airline = apps.get_model("airlines", "Airline")
    Airline.objects.filter(IATA="").update(IATA=None)
    Airline.objects.filter(ICAO="").update(ICAO=None)


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            normalize_blank_codes_to_null, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="airline",
            name="IATA",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="IATA airline codes must be exactly 2 uppercase letters and/or digits (e.g. UA, 9W).",
                        regex="^[A-Z0-9]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="airline",
            name="ICAO",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ICAO airline codes must be exactly 3 uppercase letters (e.g. UAL).",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="airline",
            index=models.Index(fields=["name"], name="airline_name_idx"),
        ),
    ]
