# Generated by Django 5.1.7 on 2026-08-17 20:10

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0003_alter_airline_options"),
    ]

    operations = [
        # Enables Postgres's pg_trgm extension, which the GIN trigram
        # index below depends on. CREATE EXTENSION IF NOT EXISTS under the
        # hood, so it's harmless if another app's migration already ran this.
        TrigramExtension(),
        migrations.AddIndex(
            model_name="airline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="airline_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
