# Generated by Django 5.1.7 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0004_airline_airline_name_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="airline",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
